### ISSUE TITLE
[Curriculum] Week 0 - Getting Started

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/study-group-curriculum#1]
## Learning Goal 

The goal of this week is to get set up with Nightcode & Quil, and get the sketch from the workshop running again. 

**Bonus Idea**: Learn how to push code to Github. Push your sketch from the workshop to the [week-0](https://github.com/clojurebridge-berlin/study-group-curriculum/blob/master/week-0/) folder. 

## Todo in preparation  

* Finish this [Readme](https://github.com/clojurebridge-berlin/study-group-curriculum/blob/master/week-0/README.md). 
* Bonus: Find an easy Git/Github tutorial, add it to the Readme.

**Comment by Realtin** [comment]
For the git/GitHub Tutorial consider Jessica Lords git-it it is a nodeschool workahopper (inside the Terminal) but there is also now an Electron Version! https://github.com/jlord/git-it-electron

**Comment by Robsteranium** [comment]
This sounds good.

I wonder if it would be nice to deploy the application somehow (to show it off to friends without needing to be sat around the laptop!).

This doesn't need to be a cljs version. I seem to recall that it was simple enough with Processing to bundle your app up as a jar that ran in the browser...
