### ISSUE TITLE
[Curriculum] Week 1 - Drawing Shapes

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/study-group-curriculum#2]
## Learning Goal

The topic of week 1 is drawing non-moving shapes with quil: circles, shapes, different colors.  A good example of this is the coloured squares example that @lislis proposed here: https://github.com/clojurebridge-berlin/organization/issues/118#issuecomment-254947958

##  Todo in preparation 

* Build a simple quil sketch that helps showcase the goal. (For example: coloured squares as suggested).
* Fill in the [Readme](https://github.com/clojurebridge-berlin/study-group-curriculum/blob/master/week-1/README.md) with instructions on how to build this sketch, and explaining the core ideas. 
* Open a PR to push your solution sketch to the [week-1] folder. 
* Think of *bonus* ideas to expend on the sketch - add these to the readme.

**Comment by Robsteranium** [comment]
Bonus idea - perhaps look at writing functions that create shapes? This could use the polygon shape (I presume that exists!) or compounds, e.g. combine a few circles to make a face!
