### ISSUE TITLE
[Curriculum] Week 2 - Animation

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/study-group-curriculum#3]
## Learning Goal

The topic of week 2 is drawing a simple animation: a moving ball, beating heart, etc. 

## Todo in preparation

* Build a simple quil sketch that helps showcase the goal. 
* Fill in the [Readme](https://github.com/clojurebridge-berlin/study-group-curriculum/blob/master/week-2/README.md) with instructions on how to build this sketch, and explaining the core ideas. 
* Open a PR to push your solution sketch to the [week-2] folder. 
* Think of *bonus* ideas to expend on the sketch - add these to the readme.

**Comment by Robsteranium** [comment]
I guess there's a few ways of achieving this, I wonder if we ought to present a few recipes for different approaches?

As a bonus it could invite the learner to consider the trade-offs (i.e. if you block the loop with an animation you can't collect mouse events), possibly with a lead-in to fun-mode (i.e. animation tick as state).

**Comment by Robsteranium** [comment]
Ah - just realised user-interaction doesn't happen until next week! Perhaps that bonus is a bit early! Well maybe this lesson could lay the groundwork...

**Comment by jellea** [comment]
I was thinking of just using `(frame-count)` for this instead of incrementing the state? So we can save state for the week after.

**Comment by vsmart** [comment]
Done 💯
