### ISSUE TITLE
[Curriculum] Week 3 - User Interaction

### ISSUE THREAD

**Issue by vsmart** [clojurebridge-berlin/study-group-curriculum#4]
## Learning goal

The topic of week 3 is to use Quil's user interaction functions to make a simple animation that the user can interact with. For example this could use the `mouse-x` and `mouse-y`, or the key event input functions. 

## Todo in preparation

* Build a simple quil sketch that helps showcase the goal.
* Fill in the [Readme](https://github.com/clojurebridge-berlin/study-group-curriculum/blob/master/week-3/README.md) with instructions on how to build this sketch, and explaining the core ideas. 
* Open a PR to push your solution sketch to the [week-3] folder. 
* Think of *bonus* ideas to expend on the sketch - add these to the readme.

**Comment by Robsteranium** [comment]
IIRC once `mouse-{x,y}` enter the sketch the animation can get pretty wild and confusing (thanks trigonometry)! I wonder if this lesson should also explain e.g. printf debugging (so you can see what the mouse position actually is etc)...

**Comment by Realtin** [comment]
here an example: https://github.com/Realtin/clojure-bridge
that was my project when I was an attendee. A rectangle that follows the mouse and changes color and size accordingly + has lines attached to the edges of the screen and the edges of the rectangle

**Comment by lislis** [comment]
@Realtin that it AWESOME!

**Comment by vsmart** [comment]
very cool! @Realtin do you want to open a pr to push it to the repo?

**Comment by Realtin** [comment]
will do!

**Comment by vsmart** [comment]
We have an example for Week 3, added in #11.
